## **Import Numpy & Make Variable 'arr1' as Array**

In [ ]:
import numpy as np
arr1 = np.array([i+1 for i in range(0,30)])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

## **Define & Reshaping Variable 'arr2' as Array**

In [ ]:
arr2 = arr1.reshape(5,6)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

## **Define Variable 'kuning' as Array 2D (2,2)**

In [ ]:
kuning = arr2[3:,4:]
kuning

array([[23, 24],
       [29, 30]])

## **Define Variable 'horz' as Array (1,5)**

In [ ]:
horz = arr2[:1,1:]
horz

array([[2, 3, 4, 5, 6]])

## **Define Variable 'vert' as Array**
## **Define and Reshaping Variable 'vert1' as Array (1,5)**

In [ ]:
vert = arr2[0:,1]
vert1 = vert.reshape(1,5)
vert1

array([[ 2,  8, 14, 20, 26]])

## **Define Variable 'merah' as Array 2D (2,5)**

In [ ]:
merah = np.concatenate((horz,vert1), axis=0)
merah

array([[ 2,  3,  4,  5,  6],
       [ 2,  8, 14, 20, 26]])